name: Build Binary

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - run: node -v
    - run: yarn -v
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - run: yarn install
    - run: yarn generate-types
    - run: yarn lint
    - run: yarn test
    - run: yarn generate-linux-binary

    - name: save pricewatch binary
      uses: actions/upload-artifact@v2
      if: !failure()
      with:
        name: pricewatch binary
        path: ./pricewatch
