name: Build Binary

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: pricewatch_test
          MYSQL_USER: pricewatch_test_user
          MYSQL_PASSWORD: pricewatch_test_pass
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Show Docker containers
      run: docker ps -a
    - name: Prepare databases for test user
      run: mysql --protocol=tcp -h localhost -P 3306 -u root -proot_password < init.sql
    - name: Show databases for pricewatch_test_user
      run: mysql --protocol=tcp -h localhost -P 3306 -u pricewatch_test_user -ppricewatch_test_pass -e "SHOW DATABASES"

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - run: node -v
    - run: yarn -v
    - run: yarn install
    - run: yarn generate-types
    - run: yarn lint
    - run: yarn test
    - run: yarn generate-linux-binary

    - name: save pricewatch binary
      uses: actions/upload-artifact@v2
      if: ${{ success() }}
      with:
        name: pricewatch binary
        path: ./pricewatch
