name: Build Binary

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - run: node -v
    - run: yarn -v
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - run: yarn install
    - run: yarn generate-types
    - run: yarn generate-linux-binary